### ISSUE TITLE
package file qLib_package_linux.json not working on latest production build hfs18.5.408

### ISSUE THREAD

**Issue by Rognva1dr** [qLab/qLib#1185]
Hi - i'm getting weird errors in shell - that go if i don't use the package.

errors as follows:
Error while parsing a menu definition file
 '/home/neil/hfs18.5.408/packages/kinefx/MainMenuCommon.xml':
Could not find the parent element 'import_files' for 'h.import_mocap'.
Cannot set order: element 'h.import_mocap' has no parent.
Cannot set order: element 'h.import_mocap' has no parent.
Could not find the parent element 'windows_menu' for 'h.open_rigtree'.
Cannot set order: element 'h.open_rigtree' has no parent.
Cannot set order: element 'h.open_rigtree' has no parent.

I believe the qlib .json file might need updating for the new Houdini production build.

Thank you

**Comment by johnnyquest** [comment]
hey @Rognva1dr thanks for the feedback, I think it also relates to #1180 -- I'll take a look soon

**Comment by Rognva1dr** [comment]
Hi @johnnyquest 

I think packages may be broken in the 408 build of houdini 18.5.

I'm trying to find out for sure.

The qLib .json package on its own works just fine; but as I add others - like Labs or MOPs etc - other packages - things break.

I will hopefully find out soon what is happening from SideFX

Thanks

**Comment by Rognva1dr** [comment]
Hi @johnnyquest 

SideFX just confirmed with me that there is a problem with packages in the latest 408 build....

Sorry for the false alarm!

Thanks

Neil

**Comment by johnnyquest** [comment]
hey @Rognva1dr thanks to getting back to me on this, that's good to know! I'll close this ticket as soon as they release a new build that fixes the issue, and I can double-check that things work again

**Comment by Rognva1dr** [comment]
Hi @johnnyquest - packages are now fixed as of daily build 18.5.415

Thanks

**Comment by revilo3d** [comment]
I'm still getting this issue when I load qLib,  but it's clashing with Renderman in my instance. If I remove the Renderman package everything works as expected.

Houdini 19.0.383 py 3.
